apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  labels:
    app  : ftps-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  selector:
    app: ftps
  ports:
    - name: port-ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: port-passv
      protocol: TCP
      port: 10100
      targetPort: 10100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
       app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app: ftps
    spec:
      containers: 
      - name: ftps
        image: ftps-image
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 10100